# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"
locale: "en-US"
title: RubyOcelot's Homepage
title_separator : "-"
subtitle: "Version 0.0"
name: "RubyOcelot"
description: >- # this means to ignore newlines until "baseurl:"
  RubyOcelot(aka loliw)'s Homepage

  OwO
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://loliw.moe" # the base hostname & protocol for your site, e.g. http://example.com
#repository: "username/repo-name"
teaser: /assets/images/teaser-default.jpg
logo: "/assets/images/logo.webp"
masthead_title: "Miaow~"
#breadcrumbs: true  # disabled by default

words_per_minute: 250
#atom_feed:
#  path: "http://feeds.feedburner.com/youFeedname"
search: true
#search_provider: algolia #no account
og_image: /assets/images/avatar.jpg
timezone: America/Los_Angeles

author:
  name: "RubyOcelot"
  avatar: "/assets/images/avatar.jpg"
  bio: >-
    Miaow~

  location: "UCI"
  links:
#    - label: "Made Mistakes"
#      icon: "fas fa-fw fa-link"
#      url: "https://mademistakes.com"
#      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RubyOcelot"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RubyOcelot"





# Build settings
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
i#ncremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  #smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: mathjax
  parse_block_html: false # true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      #start_line: 1

  html_to_native: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Reading Files
include:
  - .htaccess
  - _pages
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .github/
  - .gitignore
  - .jekyll-assets-cache
  - .sass-cache
  - .vscode
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - "LICENSE*"
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - REMOTE_README.md
  - tmp
keep_files: [".git", ".nojekyll", "README.md", "CNAME"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      #comments: true   #need plugin
      author_profile: true
      sidebar:
        nav: "side"
      toc: true
      excerpt: ""
      header:
        overlay_image: /assets/images/header-default.jpg
        overlay_filter: rgba(0, 0, 0, 0.4)
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
