name: build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Setup cache for Bundler
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          Gemfile.lock
          vendor/bundle
        key: ${{ runner.os }}-bundler-2-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-2-
    - name: Install - Bundler
      env:
        MAKE: make -j2
      run: |
        bundle install --path=vendor/bundle --jobs=4 --retry=3
        bundle clean
    - name: Build site
      run: bundle exec jekyll build --profile --trace
      env:
        JEKYLL_ENV: production
        JEKYLL_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Deploy site
      run: |
        cp REMOTE_README.md _site/README.md
        cd _site
        git init
        git config user.name "GitHub"
        git config user.email "noreply@github.com"
        git remote add deploy https://RubyOcelot:${{ secrets.GH_TOKEN }}@github.com/RubyOcelot/RubyOcelot.github.io.git >/dev/null 2>&1
        git fetch --depth=1 deploy master
        git reset --soft FETCH_HEAD
        git add --all
        git commit --message "Auto deploy from GitHub Actions build $GITHUB_RUN_NUMBER"
        git push deploy master
